# 最大反思重试次数
MAX_REFINEMENTS = 2

# Refiner 评分阈值（0-10），低于此值触发重试
REFINER_SCORE_THRESHOLD = 7

# 文档分块
CHUNK_SIZE = 1200
CHUNK_OVERLAP = 200

# 检索上下文（用于 LLM 的 context 最大 token 预算）
MAX_CONTEXT_TOKENS = 3000

# 检索
CHUNK_TOP_K = 20
COSINE_THRESHOLD = 0.6
BM25_TOP_K = 20
RRF_CONSTANT_K = 60

# Worker 名称常量
WORKER_RETRIEVAL = "retrieval"
WORKER_DOCS = "docs"
WORKER_SUMMARY = "summary"
WORKER_DATA_ANALYST = "data_analyst"

ALL_WORKERS = [WORKER_RETRIEVAL, WORKER_DOCS, WORKER_DATA_ANALYST, WORKER_SUMMARY]

# 记忆
MEMORY_EXTRACTION_TYPES = ["fact", "preference", "pattern", "template"]
WORKING_MEMORY_TTL = 24  # 小时
MEMORY_TOP_K = 5
CORE_MEMORY_WEIGHT = 0.6
WORKING_MEMORY_WEIGHT = 0.4
DEFAULT_USER_ID = "default"

# Eval
EVAL_HARD_CASE_THRESHOLD = 5
EVAL_DIMENSIONS = ["faithfulness", "relevance", "completeness"]
EVAL_MAX_RECENT_RUNS = 200
EVAL_SCORE_BUCKETS = ["0-3", "4-6", "7-8", "9-10"]
